name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      approval_required:
        description: 'Deploy to production?'
        required: true
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://adb-prod-1234567.7.azuredatabricks.net
    
    env:
      DATABRICKS_AUTH_TYPE: github-oidc
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main
      
      - name: Create deployment tag
        run: |
          git tag -a "deploy-$(date +%Y%m%d-%H%M%S)" -m "Production deployment"
          git push --tags
      
      - name: Deploy to production
        run: databricks bundle deploy --target prod
      
      - name: Verify deployment
        run: |
          databricks bundle validate --target prod
          echo "✅ Production deployment complete"
